CREATE TABLE R (
	RID INT(11),
	B INT(11),
	C INT(11),
	PRIMARY KEY (RID)
) ENGINE=InnoDB;

CREATE TABLE S (
	SID INT(11),
	RID INT(11),
	D INT(11),
	E INT(11),
	PRIMARY KEY (SID),
	FOREIGN KEY (RID) REFERENCES R(RID)
) ENGINE=InnoDB;