LOAD DATA LOCAL INFILE 'project2_R.csv'
INTO TABLE R
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\r\n';

LOAD DATA LOCAL INFILE 'project2_S.csv'
INTO TABLE S
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\r\n';